//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int id_venta { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
        public Nullable<decimal> precio_venta { get; set; }
        public string comprador_nombre { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual Vehiculo Vehiculo1 { get; set; }
    }
}
